weixin4j:
  #微信开发配置
  config:
    #开发者第三方用户唯一凭证
    appid: wxb4fa535e0584ac53
    #开发者第三方用户唯一凭证密钥
    secret: 00000000000000000000000000000000
    #公众号原始ID
    originalid:
    #消息加密方式 0:明文模式(默认), 1:兼容模式, 2:安全模式(推荐)
    encodingtype: 0
    #消息加密密钥(43位字符组成A-Za-z0-9)
    encodingaeskey: 0123456789abcedfghijklmnopqrstuvwxyzZXCVBNM
    #网页安全授权URL
    oauthUrl:
  #微信支付配置
  payConfig:
    #微信支付_商户ID，例如10000000001
    mchId:
    #微信支付_商户密钥，由商户设置32位字符
    mchKey:
    #微信支付_通知URL，异步接收微信支付结果的URL
    notifyUrl:
    #证书路径(pk12格式)，例如：/opt/cert/10000000001.pk12
    certPath:
    #证书密钥,默认为商户ID，例如：10000000001
    certSecret:
  opensslPath:
  rsaPubKeyPkcs1:
  rsaPubKeyPkcs8: